framework:
  notifier:
    chatter_transports:
    texter_transports:
    channel_policy:
      # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
      urgent: [ 'emails' ]
      high: [ 'emails' ]
      medium: [ 'emails' ]
      low: [ 'emails' ]
    admin_recipients:
      - { email: admin@example.com }
